os:
- linux
addons:
  ssh_known_hosts:
  - superfast647664.westeurope.cloudapp.azure.com
cache:
  directories:
  - "$HOME/.composer/cache"
language: php
php:
- 7.0
install:
- composer install
- cp travis.env .env
- mysql -e 'create database blog;'
- php artisan key:generate
- php artisan migrate
- php artisan db:seed
script: vendor/bin/phpunit --configuration phpunit.xml --coverage-text
deploy:
- provider: script
  skip-cleanup: true
  script:
  - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR $DEPLOY_USER@$DEPLOY_HOST:/home/kingen/superfast/git
  on:
    branch: master
notifications:
  email:
    recipients: caresilabs@gmail.com;patriknilsson1337@live.se
before_deploy:
- openssl aes-256-cbc -K $encrypted_9a32a51e45ce_key -iv $encrypted_9a32a51e45ce_iv
  -in ../deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
before_install:
- openssl aes-256-cbc -K $encrypted_9a32a51e45ce_key -iv $encrypted_9a32a51e45ce_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- cd Assignment4
