os:
- linux
addons:
  ssh_known_hosts:
  - superfast467664.westeurope.cloudapp.azure.com
cache:
  directories:
  - "$HOME/.composer/cache"
language: php
php:
- 7.0
install:
- composer install
before_script:
- cd Assignment4
script: vendor/bin/phpunit --configuration phpunit.xml --coverage-text
deploy:
- provider: script
  skip-cleanup: true
  script:
  - rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR $DEPLOY_USER@$DEPLOY_HOST:/home/kingen
  on:
    branch: master
notifications:
  email:
    recipients: caresilabs@gmail.com;patriknilsson1337@live.se
before_install:
- openssl aes-256-cbc -K $encrypted_9a32a51e45ce_key -iv $encrypted_9a32a51e45ce_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- cd Assignment4
